name: mailboar
summary: Web and API based SMTP testing
description: |
 MailBoar is an email testing tool for developers:
 * Configure your application to use MailBoar for SMTP delivery
 * View messages in the web UI, or retrieve them with the JSON API
 * Optionally release messages to real SMTP servers for delivery
version: "master"
confinement: strict
grade: stable
apps:
  mailboar:
    command: MailBoar
    plugs: [network-bind]
    daemon: simple
parts:
  mailboar:
    plugin: go
    go-packages:
      - github.com/gnyman/MailBoar
    build-packages:
      - git
